sonar.projectKey=namsee-org_todolist-api
sonar.organization=namsee-org
sonar.host.url=https://sonarcloud.io
sonar.sources=.

# Exclude non-source directories from analysis
sonar.exclusions=**/vendor/**,**/*_test.go,**/tools/**,**/scripts/**,**/api/**/*.gen.go

# Go test coverage report (if you generate one)
# sonar.go.coverage.reportPaths=coverage.out

# Test file inclusions
sonar.test.inclusions=**/*_test.go
