name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarCloud Scan
        uses: namsee-org/cicd-platform/.github/actions/sonarqube@main
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
